### ISSUE TITLE
Discrepancy in stats/latest count when # is added to total count

### ISSUE THREAD

**Issue by siddharthsrivastava** [amodm/api-covid19-in#22]
Hi

Right now, the total count on MoHFW is 1251 (screenshot attached) while that from API is 1205 (screenshot attached). I have noticed this behaviour when a # is added by MoHFW to the table. Can we handle it ? I have noticed that they mostly use # to indicate unassigned cases to state.

![image](https://user-images.githubusercontent.com/534879/77949536-bdc2ed80-72e4-11ea-9288-22f35df2f92f.png)

![image](https://user-images.githubusercontent.com/534879/77949575-cddacd00-72e4-11ea-98e5-6fa55788433c.png)

**Comment by amodm** [comment]
Yes, this happens when particular cases are not yet assigned to states on MoHW. In the image below, you can see that the delta of 46 cases can be attributed to it. 

<img width="741" alt="Screenshot 2020-03-31 at 12 23 47 AM" src="https://user-images.githubusercontent.com/1546858/77950286-e7304900-72e5-11ea-98df-d17d5f63b793.png">

I had put in a hack to deal with such scenarios, but as always MoHFW changed the format. I'll include it again, but this is a very fragile logic to deal with 😞. Do you have any better ideas?

**Comment by siddharthsrivastava** [comment]
ah yes, I had noticed. Foreigner count also removed (now it is mentioned at the top of the table). 
May be just check for the # and parse the column headers for confirmed and Total/Indian/Foreign, whichever column have those, will contain the final count against the bottom row containing "Total number of confirmed cases in India" which haven't changed I guess since the beginning. So there are high chances that a combination of confirmed + (Total/Indian/Foreign) & last row "Total number of confirmed cases in India" could be more robust. 

Thanks for updating the API though.
