### ISSUE TITLE
Data updation

### ISSUE THREAD

**Issue by VinitSawant09** [amodm/api-covid19-in#37]
Not able to fetch the latest/updated data for the below(data available till only 24th June):

1) https://api.rootnet.in/covid19-in/stats/latest
2) https://api.rootnet.in/covid19-in/stats/history

Is the updation / refreshing of data manually done ?

**Comment by amodm** [comment]
Thx for bringing this to my notice. This is fixed now.

The data is updated automatically, which is probably why I missed this. It seems mohfw site briefly moved to Cloudflare, and then moved out. Cloudflare workers seems to still remember that it's hosted on it, but because the site has moved on, the update craps out.

I've fixed it by moving update calls out of Cloudflare.
