### ISSUE TITLE
API data not updated.

### ISSUE THREAD

**Issue by VinitSawant09** [amodm/api-covid19-in#38]
Hi again, 

the following APIs are not fetching the latest data. 

1) https://api.rootnet.in/covid19-in/stats/latest

There is a lag in both summary as well unofficial-summary fetched from covid19india.org. Lat updated time is showing latest time but data is lagging.

{
  "success": true,
  "data": {
    "summary": {
      "total": 1287945,
      "confirmedCasesIndian": 1287897,
      "confirmedCasesForeign": 48,
      "discharged": 817209,
      "deaths": 30601,
      "confirmedButLocationUnidentified": 0
    },
    "unofficial-summary": [
      {
        "source": "covid19india.org",
        "total": 1239684,
        "recovered": 784267,
        "deaths": 29890,
        "active": 425113
      }
    ],
.
.
.

 "lastRefreshed": "2020-07-24T15:54:32.663Z",
  "lastOriginUpdate": "2020-07-24T02:30:00.000Z"
}

2) https://api.rootnet.in/covid19-in/stats/testing/history (no new entries after 22nd July)

I guess there might be a lag of a day or more as confirmed cases have a difference of around 1 lakh.

Thanks

**Comment by amodm** [comment]
Thanks for reporting @VinitSawant09. I've fixed this.

covid19india.org team's data is fetched using a private google sheet on which they collaborate. A new sheet gets used every few days because of the size of data. I've not gotten around to automating the link change yet, so some times I end up discovering this through a bug report like this.
