### ISSUE TITLE
COVID19 Stats History Data same for Sept 24th and Sept 25th

### ISSUE THREAD

**Issue by akashagl92** [amodm/api-covid19-in#46]
The API - https://api.rootnet.in/covid19-in/stats/history - has the same data for Sept 24th and 25th.

{
      "day": "2020-09-24",
      "summary": {
        "total": 5818570,
        "confirmedCasesIndian": 5818522,
        "confirmedCasesForeign": 48,
        "discharged": 4756164,
        "deaths": 92290,
        "confirmedButLocationUnidentified": 0
      }

{
      "day": "2020-09-25",
      "summary": {
        "total": 5818570,
        "confirmedCasesIndian": 5818522,
        "confirmedCasesForeign": 48,
        "discharged": 4756164,
        "deaths": 92290,
        "confirmedButLocationUnidentified": 0
      }

The regional data accordingly will also be same as summary data is same.

**Comment by amodm** [comment]
This is very weird, but it looks like there was an issue with MoHFW data itself. You can see even in wayback machine, that even though the summarised total looks different between the days, the underlying data seems to have not changed:

[Sep 24](https://web.archive.org/web/20200924102952/https://www.mohfw.gov.in/)
[Sep 25](https://web.archive.org/web/20200925095131/https://www.mohfw.gov.in/)

Since I scrape from the raw data, doesn't look possible for me to correct this, except may be to split up the delta between 23-26 into equal parts 😞. I don't like modifying the data received from upstream, so won't be adjusting it in this way, instead will retain the data as is.
